module.exports = {
  docs: {
    Websiteshot: [
      "websiteshot/introduction",
      "websiteshot/getting-started",
      "websiteshot/console",
      "websiteshot/whats-new",
    ],
    Features: [
      "features/collections",
      "features/templates",
      "features/filters",
      "features/scheduled-jobs",
      "features/click-events",
      "features/guarded-websites",
    ],
    Guides: [
      "guides/quickstart",
      "guides/simple-script",
      "guides/github-action",
      "guides/track-progress",
      "guides/social-share",
    ],
    Examples: [
      "examples/natural",
      "examples/shadow",
      "examples/macos-simple-dark",
      "examples/combined-effects",
      "examples/resize",
      "examples/blur",
      "examples/crop-area",
    ],
    API: [],
  },
  api: {
    "Getting Started": ["api/introduction"],
    Jobs: [
      "api/jobs/create-screenshot-job",
      "api/jobs/create-with-template",
      "api/jobs/get-screenshot-jobs",
    ],
    Screenshots: ["api/screenshots/get-screenshots"],
    Types: [
      "api/types/blur-options",
      "api/types/click",
      "api/types/color",
      "api/types/effect-config",
      "api/types/job-result",
      "api/types/login-parameter",
      "api/types/margin-options",
      "api/types/meta",
      "api/types/project-job",
      "api/types/resize-options",
      "api/types/rounded-corners-options",
      "api/types/screenshot-parameter",
      "api/types/schedule-description",
      "api/types/shadow-options",
      "api/types/url-config",
    ],
  },
};
