name: publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  # Used by docusaurus publish-site command
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_USERNAME: urbanisierung
  REPO: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          # Configure git client
          echo "Git repo - $REPO"
          echo "Git user - $GIT_USERNAME"
          echo "Event name - ${{github.event_name }}"
          git config --global user.email "$GIT_USERNAME@users.noreply.github.com"
          git config --global user.name "$GIT_USERNAME"
          echo "machine github.com login $GIT_USERNAME password $GITHUB_TOKEN" > ~/.netrc
          # Run docusaurus-publish
          GIT_USER=$GIT_USERNAME npm run deploy
